#!/bin/sh
# titan-cron entrypoint
# Builds /etc/crontabs/root from environment variables and starts crond.
#
# Required env:
#   CRON_SECRET     — header token for /api/cron/* endpoints
#   TITAN_APP_URL   — base URL for titan-app (default http://titan-app:3100)

set -eu

: "${CRON_SECRET:?CRON_SECRET is required}"
TITAN_APP_URL="${TITAN_APP_URL:-http://titan-app:3100}"

# Common curl options:
# -fsS  — fail on HTTP error, silent except on error, show error message
# --max-time 60 — abort if takes longer than 60s
# || true — never let cron fail; we log success/failure to stdout via crond
CURL="curl -fsS --max-time 60 -X POST -H 'x-cron-secret: ${CRON_SECRET}'"

cat > /etc/crontabs/root <<EOF
# TITAN cron schedule (Asia/Taipei timezone)
# Generated by cron-entrypoint.sh

# Every 1 minute — drain push notification queue (Issue #1354)
* * * * * ${CURL} ${TITAN_APP_URL}/api/cron/push-dispatch || true

# Every 5 minutes — drain audit queue (prevents Redis OOM)
*/5 * * * * ${CURL} ${TITAN_APP_URL}/api/cron/audit-queue-drain || true

# Every 15 minutes — trigger email notifications
*/15 * * * * ${CURL} ${TITAN_APP_URL}/api/cron/email-notifications || true

# 08:00 daily — daily digest (push notifications)
0 8 * * * ${CURL} ${TITAN_APP_URL}/api/cron/daily-digest || true

# 08:00 daily — daily personal digest email (Issue #1321)
0 8 * * * ${CURL} ${TITAN_APP_URL}/api/cron/email-digest || true

# 16:00 Fridays — weekly manager summary email (Issue #1321)
0 16 * * 5 ${CURL} ${TITAN_APP_URL}/api/cron/weekly-manager-digest || true

# 17:00 weekdays — daily reminder
0 17 * * 1-5 ${CURL} ${TITAN_APP_URL}/api/cron/daily-reminder || true

# 02:00 daily — stale task scan
0 2 * * * ${CURL} ${TITAN_APP_URL}/api/cron/stale-task-scan || true

# 08:30 Mondays — weekly verification reminder
30 8 * * 1 ${CURL} ${TITAN_APP_URL}/api/cron/verification-reminder || true
EOF

echo "[titan-cron] Crontab installed:"
cat /etc/crontabs/root
echo "[titan-cron] Starting crond..."

# -f foreground; -L /dev/stdout send logs to stdout (visible via docker logs)
exec crond -f -L /dev/stdout
